# Generated by Django 4.2.7 on 2026-06-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admission_education_draft_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSubmitInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Title displayed at the top of the submit confirmation popup.', max_length=200)),
                ('notice', models.TextField(help_text='Instruction text students must read before confirming submission.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers are used first when multiple instructions are active.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Submit application instruction',
                'verbose_name_plural': 'Submit application instructions',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
