# Generated by Django 4.2.7 on 2026-06-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_default_submit_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsubmitinstruction',
            name='notice',
            field=models.TextField(help_text='Rich-text instruction students must read before confirming submission.'),
        ),
    ]
