# Generated by Django 4.2.7 on 2026-06-14 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('reset_key', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'AdminUsers',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('otp_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PasswordResetOTP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('program_type', models.CharField(blank=True, max_length=200)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Students',
                'ordering': ['-created_date'],
            },
        ),
    ]
