# Generated by Django 4.2.7 on 2026-06-15 06:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_socialmedialink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Instruction details shown on the home page.')),
                ('attached_file', models.FileField(blank=True, help_text='Optional PDF, image, or document attachment.', null=True, upload_to=accounts.models.home_content_upload_path)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Important instruction',
                'verbose_name_plural': 'Important instructions',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Notice text shown in the scrolling ticker.')),
                ('attached_file', models.FileField(blank=True, help_text='Optional PDF, image, or document attachment.', null=True, upload_to=accounts.models.home_content_upload_path)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. Notice is hidden after this date and time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
