# Generated by Django 4.2.7 on 2026-06-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_importantinstruction_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpdeskIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('registration_no', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Helpdesk issue',
                'verbose_name_plural': 'Helpdesk issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpdeskOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_hours', models.CharField(blank=True, help_text='e.g. Mon–Fri, 10:00 AM – 4:00 PM', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Helpdesk officer',
                'verbose_name_plural': 'Helpdesk officers',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
