# Generated by Django 4.2.7 on 2026-06-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_helpdeskissue_helpdeskofficer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinstruction',
            name='description',
            field=models.TextField(help_text='Rich-text instruction details shown on the home page.'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(help_text='Rich-text notice content shown in the scrolling ticker.'),
        ),
    ]
