server {
    listen 80;
    server_name _; # Replace with your domain name or EC2 Public IP

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /home/ubuntu/django_ccp/staticfiles/;
    }

    location /media/ {
        alias /home/ubuntu/django_ccp/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
