# Generated by Django 4.2.7 on 2026-06-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('session_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'AcademicSessions',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('college_name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Colleges',
                'db_table': 'Colleges',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('program_code', models.CharField(blank=True, max_length=50)),
                ('program_name', models.CharField(max_length=150)),
                ('program_level', models.CharField(blank=True, max_length=20)),
                ('is_nep_compliant', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('program_type', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=250)),
                ('course_type_1', models.CharField(blank=True, max_length=50)),
                ('course_type_2', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Program_Courses',
                'ordering': ['sort_order', 'legacy_id'],
            },
        ),
    ]
