# Generated by Django 4.2.7 on 2026-06-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_programcourse_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_heading', models.CharField(help_text='e.g. B.Sc. Bio Group', max_length=150)),
                ('group_key', models.CharField(help_text='Unique key stored in applications, e.g. bio_a', max_length=50)),
                ('group_label', models.CharField(help_text='Short label shown to students, e.g. Group A', max_length=100)),
                ('departments', models.TextField(help_text='Comma-separated department names. DSC courses in these departments become compulsory when the group is selected.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_groups', to='courses.program')),
            ],
            options={
                'verbose_name': 'Subject Group',
                'verbose_name_plural': 'Subject Groups',
                'ordering': ['sort_order', 'section_heading', 'group_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='programsubjectgroup',
            constraint=models.UniqueConstraint(fields=('program', 'group_key'), name='unique_program_subject_group_key'),
        ),
    ]
