# Generated by Django 4.2.7 on 2026-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_seed_program_subject_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcourse',
            name='subject_groups',
            field=models.ManyToManyField(blank=True, help_text='B.Sc. subject groups this course belongs to (for DSC group selection on admission).', related_name='courses', to='courses.programsubjectgroup'),
        ),
    ]
