# Generated by Django 4.2.7 on 2026-06-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_assign_course_subject_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCourseInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional short heading displayed in bold above the message.', max_length=200)),
                ('message', models.TextField(help_text='Instruction text for students selecting courses for this program.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Order when multiple instructions exist for the same program.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instructions', to='courses.program')),
            ],
            options={
                'verbose_name': 'Course selection instruction',
                'verbose_name_plural': 'Course selection instructions',
                'ordering': ['program__program_name', 'sort_order', 'id'],
            },
        ),
    ]
