# Generated by Django 4.2.7 on 2026-06-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_program_course_instruction'),
    ]

    def seed_ba_geography_pair(apps, schema_editor):
        ProgramCourse = apps.get_model('courses', 'ProgramCourse')
        theory = ProgramCourse.objects.filter(
            program_type='B.A. First Semester',
            course_name='Fundamental of Physical Geography',
        ).first()
        practical = ProgramCourse.objects.filter(
            program_type='B.A. First Semester',
            course_name='Geography Lab - Cartography- Tools and Techniques',
        ).first()
        if theory and practical:
            theory.auto_select_course = practical
            theory.save(update_fields=['auto_select_course'])

    operations = [
        migrations.AddField(
            model_name='programcourse',
            name='auto_select_course',
            field=models.ForeignKey(blank=True, help_text='Linked course auto-selected and locked when this course is checked (e.g. theory paper → practical/lab).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_selected_by_courses', to='courses.programcourse'),
        ),
        migrations.RunPython(seed_ba_geography_pair, migrations.RunPython.noop),
    ]
