# Generated by Django 4.2.7 on 2026-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_program_max_optional_course_selections'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='show_department_in_course_name',
            field=models.BooleanField(default=True, help_text='When enabled, department is shown before the course name on the admission form and course lists (e.g. Hindi — Paper I).'),
        ),
    ]
